//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SagicorNow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SagicorNow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TXLife xmlns=&quot;http://ACORD.org/Standards/Life/2&quot;&gt;
        ///	&lt;TXLifeRequest&gt;
        ///		&lt;TransRefGUID&gt;
        ///			&lt;&lt;transaction-guid&gt;&gt;&lt;/TransRefGUID&gt;
        ///					&lt;TransType tc=&quot;111&quot;&gt;OLI_TRANS_ILLCAL&lt;/TransType&gt;
        ///					&lt;IllustrationRequest&gt;
        ///						&lt;RequestBasis&gt;
        ///							&lt;InterestAssumption tc=&quot;2&quot;&gt;OLI_INTASSUM_CURRENT&lt;/InterestAssumption&gt;
        ///							&lt;MortalityAssumption tc=&quot;3&quot;&gt;OLI_MORTASSMP_CURRENT&lt;/MortalityAssumption&gt;
        ///							&lt;VectorRequest&gt;
        ///								&lt;VectorItem&gt;
        ///									&lt;VectorType tc=&quot;5&quot;&gt;VECTOR_SCHEDMODALPREM&lt;/VectorType&gt;
        ///								&lt;/Ve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FS_Quote_Request_Template {
            get {
                return ResourceManager.GetString("FS_Quote_Request_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TXLife xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://ACORD.org/Standards/Life/2&quot;&gt;
        ///  &lt;TXLifeRequest&gt;
        ///    &lt;TransRefGUID&gt;&lt;&lt;transaction-guid&gt;&gt;&lt;/TransRefGUID&gt;
        ///    &lt;TransType tc=&quot;111&quot;&gt;OLI_TRANS_ILLCAL&lt;/TransType&gt;
        ///    &lt;IllustrationRequest&gt;
        ///      &lt;RequestBasis&gt;
        ///        &lt;VectorRequest&gt;
        ///          &lt;VectorSetType tc=&quot;2&quot;&gt;OLI_VECTORSET_ALL&lt;/VectorSetType&gt;
        ///        &lt;/VectorRequest&gt;
        ///      &lt;/RequestBasis&gt;
        ///    &lt;/IllustrationRequest&gt;
        ///    &lt;OLifE&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FS_Quote_Request_Template2 {
            get {
                return ResourceManager.GetString("FS_Quote_Request_Template2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:a=&quot;http://www.w3.org/2005/08/addressing&quot;&gt;
        ///  &lt;s:Header&gt;
        ///    &lt;a:Action s:mustUnderstand=&quot;1&quot;&gt;http://ACORD.org/Standards/Life/2/ProcessTXLifeRequest/ProcessTXLifeRequest&lt;/a:Action&gt;
        ///    &lt;a:MessageID&gt;urn:uuid:523f0285-4099-457d-a33c-afe5d59f19bf&lt;/a:MessageID&gt;
        ///    &lt;a:ReplyTo&gt;
        ///      &lt;a:Address&gt;http://www.w3.org/2005/08/addressing/anonymous&lt;/a:Address&gt;
        ///    &lt;/a:ReplyTo&gt;
        ///    &lt;a:To s:mustUnderstand=&quot;1&quot;&gt;https://illustration.test.sagicorlifeusa.co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FS_Quote_Request_Template3 {
            get {
                return ResourceManager.GetString("FS_Quote_Request_Template3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:a=&quot;http://www.w3.org/2005/08/addressing&quot;&gt;
        ///	&lt;s:Header&gt;
        ///		&lt;a:Action s:mustUnderstand=&quot;1&quot;&gt;http://ACORD.org/Standards/Life/2/ProcessTXLifeRequest/ProcessTXLifeRequest&lt;/a:Action&gt;
        ///		&lt;a:MessageID&gt;urn:uuid:&lt;&lt;uuid&gt;&gt;&lt;/a:MessageID&gt;
        ///		&lt;a:ReplyTo&gt;
        ///			&lt;a:Address&gt;http://www.w3.org/2005/08/addressing/anonymous&lt;/a:Address&gt;
        ///		&lt;/a:ReplyTo&gt;
        ///		&lt;a:To s:mustUnderstand=&quot;1&quot;&gt;https://illustration.test.sagicorlifeusa.com/SLI6/Core/Acord/TXLifeService.svc&lt;/a:To&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FS_Quote_Request_Template4 {
            get {
                return ResourceManager.GetString("FS_Quote_Request_Template4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:a=&quot;http://www.w3.org/2005/08/addressing&quot;&gt;
        ///	&lt;s:Header&gt;
        ///		&lt;a:Action s:mustUnderstand=&quot;1&quot;&gt;http://ACORD.org/Standards/Life/2/ProcessTXLifeRequest/ProcessTXLifeRequest&lt;/a:Action&gt;
        ///		&lt;a:MessageID&gt;urn:uuid:&lt;&lt;uuid&gt;&gt;&lt;/a:MessageID&gt;
        ///		&lt;a:ReplyTo&gt;
        ///			&lt;a:Address&gt;http://www.w3.org/2005/08/addressing/anonymous&lt;/a:Address&gt;
        ///		&lt;/a:ReplyTo&gt;
        ///		&lt;a:To s:mustUnderstand=&quot;1&quot;&gt;https://illustration.test.sagicorlifeusa.com/SLI6/Core/Acord/TXLifeService.svc&lt;/a:To&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FS_Quote_Request_Template5 {
            get {
                return ResourceManager.GetString("FS_Quote_Request_Template5", resourceCulture);
            }
        }
    }
}
