//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltNewBusinessService
{

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ServiceModel.ServiceContractAttribute(Namespace = "http://InsuranceTechnologies.com/Acord/ServiceContracts/V2_23_0/", ConfigurationName = "NewBusiness")]
	public interface NewBusiness
	{

		// CODEGEN: Generating message contract since element name request from namespace http://InsuranceTechnologies.com/Acord/ServiceContracts/V2_23_0/ is not marked nillable
		[System.ServiceModel.OperationContractAttribute(Action = "http://InsuranceTechnologies.com/Acord/ServiceContracts/V2_23_0/NewBusiness/Submi" +
			"tNewBusinessApplication", ReplyAction = "http://InsuranceTechnologies.com/Acord/ServiceContracts/V2_23_0/NewBusiness/Submi" +
			"tNewBusinessApplicationResponse")]
		SubmitNewBusinessApplicationResponse SubmitNewBusinessApplication(SubmitNewBusinessApplicationRequest request);

		[System.ServiceModel.OperationContractAttribute(Action = "http://InsuranceTechnologies.com/Acord/ServiceContracts/V2_23_0/NewBusiness/Submi" +
			"tNewBusinessApplication", ReplyAction = "http://InsuranceTechnologies.com/Acord/ServiceContracts/V2_23_0/NewBusiness/Submi" +
			"tNewBusinessApplicationResponse")]
		System.Threading.Tasks.Task<SubmitNewBusinessApplicationResponse> SubmitNewBusinessApplicationAsync(SubmitNewBusinessApplicationRequest request);
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	public partial class SubmitNewBusinessApplicationRequest
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "SubmitNewBusinessApplication", Namespace = "http://InsuranceTechnologies.com/Acord/ServiceContracts/V2_23_0/", Order = 0)]
		public SubmitNewBusinessApplicationRequestBody Body;

		public SubmitNewBusinessApplicationRequest()
		{
		}

		public SubmitNewBusinessApplicationRequest(SubmitNewBusinessApplicationRequestBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://InsuranceTechnologies.com/Acord/ServiceContracts/V2_23_0/")]
	public partial class SubmitNewBusinessApplicationRequestBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public byte[] request;

		public SubmitNewBusinessApplicationRequestBody()
		{
		}

		public SubmitNewBusinessApplicationRequestBody(byte[] request)
		{
			this.request = request;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
	public partial class SubmitNewBusinessApplicationResponse
	{

		[System.ServiceModel.MessageBodyMemberAttribute(Name = "SubmitNewBusinessApplicationResponse", Namespace = "http://InsuranceTechnologies.com/Acord/ServiceContracts/V2_23_0/", Order = 0)]
		public SubmitNewBusinessApplicationResponseBody Body;

		public SubmitNewBusinessApplicationResponse()
		{
		}

		public SubmitNewBusinessApplicationResponse(SubmitNewBusinessApplicationResponseBody Body)
		{
			this.Body = Body;
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://InsuranceTechnologies.com/Acord/ServiceContracts/V2_23_0/")]
	public partial class SubmitNewBusinessApplicationResponseBody
	{

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
		public byte[] SubmitNewBusinessApplicationResult;

		public SubmitNewBusinessApplicationResponseBody()
		{
		}

		public SubmitNewBusinessApplicationResponseBody(byte[] SubmitNewBusinessApplicationResult)
		{
			this.SubmitNewBusinessApplicationResult = SubmitNewBusinessApplicationResult;
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public interface NewBusinessChannel : NewBusiness, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public partial class NewBusinessClient : System.ServiceModel.ClientBase<NewBusiness>, NewBusiness
	{

		public NewBusinessClient()
		{
		}

		public NewBusinessClient(string endpointConfigurationName) :
				base(endpointConfigurationName)
		{
		}

		public NewBusinessClient(string endpointConfigurationName, string remoteAddress) :
				base(endpointConfigurationName, remoteAddress)
		{
		}

		public NewBusinessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
				base(endpointConfigurationName, remoteAddress)
		{
		}

		public NewBusinessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
				base(binding, remoteAddress)
		{
		}

		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		SubmitNewBusinessApplicationResponse NewBusiness.SubmitNewBusinessApplication(SubmitNewBusinessApplicationRequest request)
		{
			return base.Channel.SubmitNewBusinessApplication(request);
		}

		public byte[] SubmitNewBusinessApplication(byte[] request)
		{
			SubmitNewBusinessApplicationRequest inValue = new SubmitNewBusinessApplicationRequest();
			inValue.Body = new SubmitNewBusinessApplicationRequestBody();
			inValue.Body.request = request;
			SubmitNewBusinessApplicationResponse retVal = ((NewBusiness)(this)).SubmitNewBusinessApplication(inValue);
			return retVal.Body.SubmitNewBusinessApplicationResult;
		}

		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		System.Threading.Tasks.Task<SubmitNewBusinessApplicationResponse> NewBusiness.SubmitNewBusinessApplicationAsync(SubmitNewBusinessApplicationRequest request)
		{
			return base.Channel.SubmitNewBusinessApplicationAsync(request);
		}

		public System.Threading.Tasks.Task<SubmitNewBusinessApplicationResponse> SubmitNewBusinessApplicationAsync(byte[] request)
		{
			SubmitNewBusinessApplicationRequest inValue = new SubmitNewBusinessApplicationRequest();
			inValue.Body = new SubmitNewBusinessApplicationRequestBody();
			inValue.Body.request = request;
			return ((NewBusiness)(this)).SubmitNewBusinessApplicationAsync(inValue);
		}
	}

}